#!/usr/bin/env python3
"""EXP-P03 聚合:raw jsonl → derived 稳定性表(mean±std over seeds)。"""
import glob, json, statistics as st, sys, re
P = "data/raw/EXP-P03"
rows = {}
for f in sorted(glob.glob(f"{P}/*_radix_*.jsonl")):
    arm = "on" if "_radix_on_" in f else "off"
    for line in open(f):
        if not line.startswith("{"): continue
        d = json.loads(line)
        key = (arm, d["concurrency"], d["prefix_len"])
        rows.setdefault(key, []).append(d)
out = open("data/derived/exp_p03_ttft_vs_prefix.csv", "w")
out.write(f"# derived from {P}/*_radix_*.jsonl (3 seeds/point), generated by scripts/aggregate_p03.py\n")
out.write("arm,concurrency,prefix_len,rounds,ttft_p50_mean_ms,ttft_p50_std_ms,ttft_mean_mean_ms,cached_expected,cached_ok_all\n")
for (arm, c, pl), ds in sorted(rows.items()):
    p50s = [d["ttft_ms_p50"] for d in ds]; means = [d["ttft_ms_mean"] for d in ds]
    # cached 校验:预热后每请求 cached 应=prefix_len(on)或缺失(off);首请求外全查
    ok = True
    for d in ds:
        for cv in d["cached_tokens"]:
            v = cv or 0
            if arm == "on" and pl > 0 and v != pl: ok = False
            if (arm == "off" or pl == 0) and v != 0: ok = False
    out.write(f"{arm},{c},{pl},{len(ds)},{st.mean(p50s):.2f},{st.stdev(p50s):.2f},{st.mean(means):.2f},{pl if arm=='on' else 0},{ok}\n")
    print(f"{arm:3s} c{c} pl={pl:5d} p50={st.mean(p50s):6.2f}±{st.stdev(p50s):4.2f} ms mean={st.mean(means):6.2f} cached_ok={ok}")
# 归因交叉:ON 臂 /metrics 的 device_hit vs input token 计数
m = glob.glob(f"{P}/*_radix_on_metrics.txt")
if m:
    txt = open(m[0]).read()
    for pat in ["device_hit", 'mode="input"', "cache_hit_rate"]:
        for line in txt.splitlines():
            if pat in line and not line.startswith("#"):
                print("METRICS:", line.strip())
