#!/usr/bin/env python3
"""P03/P07 聚合:bench_prefix raw jsonl → derived 稳定性表(mean±std over seeds)。
用法:aggregate_p03.py [EXP-P03|EXP-P07] [out.csv]

职责三件:①按 (臂, 并发, prefix_len) 归组 3 seeds,产出 p50 的 mean±std;
②cached 闭环硬校验(cached_ok_all 列,见下);③打印 /metrics 快照中的
device_hit 行,供与客户端 Σcached_tokens 对账——EXP-P07 锚:引擎计数器
device_hit=466,944 与 Σcached 逐 token 相等,0.6B/8B 双复现。
臂名从文件名取(_radix_on_/_radix_off_):raw 命名即协议编码,聚合不读参数。
cached_ok_all 是数据有效性 gate:任一请求违反"on 臂恰=prefix_len、off 臂或
pl=0 恰=0"即整格 False——命中数不对说明协议被破坏(残树/预热失败/中间层
改写),该格数字不得进对外文档。
"""
import glob, json, statistics as st, sys, re
P = f"data/raw/{sys.argv[1] if len(sys.argv)>1 else 'EXP-P03'}"
rows = {}
for f in sorted(glob.glob(f"{P}/*_radix_*.jsonl")):
    arm = "on" if "_radix_on_" in f else "off"
    for line in open(f):
        if not line.startswith("{"): continue   # 跳过 provenance 首行等非 JSON 行
        d = json.loads(line)
        key = (arm, d["concurrency"], d["prefix_len"])
        rows.setdefault(key, []).append(d)
out = open(sys.argv[2] if len(sys.argv)>2 else "data/derived/exp_p03_ttft_vs_prefix.csv", "w")
out.write(f"# derived from {P}/*_radix_*.jsonl (3 seeds/point), generated by scripts/aggregate_p03.py\n")
out.write("arm,concurrency,prefix_len,rounds,ttft_p50_mean_ms,ttft_p50_std_ms,ttft_mean_mean_ms,cached_expected,cached_ok_all\n")
for (arm, c, pl), ds in sorted(rows.items()):
    p50s = [d["ttft_ms_p50"] for d in ds]; means = [d["ttft_ms_mean"] for d in ds]
    # 闭环校验:计时臂全部请求逐个查(预热请求不落 raw)。on 臂预热已种树,
    # 每请求 cached 必须恰=prefix_len;off 臂或 pl=0 必须恰=0(usage 缺失归 0)。
    ok = True
    for d in ds:
        for cv in d["cached_tokens"]:
            v = cv or 0
            if arm == "on" and pl > 0 and v != pl: ok = False
            if (arm == "off" or pl == 0) and v != 0: ok = False
    out.write(f"{arm},{c},{pl},{len(ds)},{st.mean(p50s):.2f},{st.stdev(p50s):.2f},{st.mean(means):.2f},{pl if arm=='on' else 0},{ok}\n")
    print(f"{arm:3s} c{c} pl={pl:5d} p50={st.mean(p50s):6.2f}±{st.stdev(p50s):4.2f} ms mean={st.mean(means):6.2f} cached_ok={ok}")
# 归因交叉:ON 臂 /metrics 快照的 device_hit / cache_hit_rate 行原样打印,
# 与上面客户端侧 Σcached 人工对账(两套独立计数必须逐 token 相等)。
m = glob.glob(f"{P}/*_radix_on_metrics.txt")
if m:
    txt = open(m[0]).read()
    for pat in ["device_hit", 'mode="input"', "cache_hit_rate"]:
        for line in txt.splitlines():
            if pat in line and not line.startswith("#"):
                print("METRICS:", line.strip())
